steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build Docker Image
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/finance-api-img:1.1"
      - "."
    dir: "."

  - name: "gcr.io/cloud-builders/docker"
    id: Push Docker Image
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/finance-api-img:1.1"
images:
  - "gcr.io/$PROJECT_ID/finance-api-img:1.1"
timeout: "1200s"
