version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: crunchcat-api-img:1.2
    container_name: crunchcat-api
    ports:
      - "3000:3000"
    environment:
      - DB_URL_CONTAINER=mongodb://localhost:27017/crunchcat
      # - NODE_ENV=development
      # volumes:
      # - .:/usr/src/app  
    restart: always
